apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: tanzu-java-web-app
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: tanzu-java-web-app
spec:
  params:
  - name: annotations
    value:
      autoscaling.knative.dev/minScale: "0"
  source:
    git:
      url: https://github.com/asaikali/tanzu-java-web-app.git
      ref:
        branch: main
        

        
# tanzu apps workload list -n dev
# tanzu apps workload create -f workload.yaml -n dev
# tanzu apps workload update -f workload.yaml -n dev
# tanzu apps workload get tanzu-java-web-app -n dev
# tanzu apps workload tail tanzu-java-web-app -n dev --since 1h
# tanzu apps workload delete tanzu-java-web-app -n dev

# kubectl tree workload tanzu-java-web-app -n dev
