apiVersion: v1
kind: Secret
metadata:
 name: envoy-overlay
 namespace: tap-install
stringData:
 custom-package-overlay.yml: |
  #@ load("@ytt:overlay", "overlay")
  
  #@overlay/match by=overlay.subset({"kind": "Deployment", "metadata": {"name": "envoy"}})
  ---
  spec:
    #@overlay/replace
    replicas: 1
