apiVersion: v1
kind: Secret
metadata:
 name: tailscale-overlay
 namespace: tap-install
stringData:
 custom-package-overlay.yml: |
  #@ load("@ytt:overlay", "overlay")
  #@overlay/match by=overlay.subset({"kind": "Service", "metadata": {"name": "envoy"}})
  ---
  spec:
    #@overlay/match missing_ok=True
    loadBalancerClass: tailscale
