apiVersion: v1
kind: Secret
metadata:
 name: contour-overlay
 namespace: tap-install
stringData:
 custom-package-overlay.yml: |
  #@ load("@ytt:overlay", "overlay")
  
  #@overlay/match by=overlay.subset({"kind": "Deployment", "metadata": {"name": "contour"}})
  ---
  spec:
    #@overlay/replace
    replicas: 1
