#@ load("@ytt:data", "data")

profile: full

#! Installation fails if this is not set to true. Not a string.
ceip_policy_disclosed: true

package_overlays:
  - name: contour
    secrets:
      - name: contour-overlay
      
shared:
  ingress_domain: #@ data.values.INGRESS_DOMAIN
  image_registry:
    #!  To be used by Build Service by appending "/buildservice" and used by Supply chain by appending "/workloads".
    project_path: #@ data.values.WORKLOAD_REPO
    secret:
      name: "workload-registry"
      namespace: "tap-install"

contour:
  envoy:
    service:
      type: NodePort

supply_chain: basic

#@ baseUrl = "https://tap-gui." + data.values.INGRESS_DOMAIN
tap_gui:
  service_type: ClusterIP
  app_config:
    app:
      baseUrl: #@ baseUrl
    catalog:
      locations:
        - type: url
          target: #@ data.values.CATALOG_INFO
    backend:
      baseUrl: #@ baseUrl
      cors:
        origin: #@ baseUrl
    auth:
      environment: development
      providers:
        github:
          development:
            clientId: #@ data.values.GITHUB_CLIENT_ID
            clientSecret: #@ data.values.GITHUB_CLIENT_SECRET

#! this will mean that when tap package is delete it deletes all the components of crossplane 
#! see docs at https://docs.vmware.com/en/VMware-Tanzu-Application-Platform/1.7/tap/crossplane-how-to-guides-delete-resources.html
crossplane:
  orphan_resources: false